### ISSUE TITLE
An error occurred in colossalai when starting training img

### ISSUE THREAD

**Issue by hjchen2** [NUS-HPC-AI-Lab/OpenDiT#105]
sh train_img.sh

```shell
Traceback (most recent call last):
  File "/data/home/chenhoujiang/OpenDiT/train.py", line 17, in <module>
    from colossalai.booster import Booster
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/booster/__init__.py", line 2, in <module>
    from .booster import Booster
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/booster/booster.py", line 17, in <module>
    from .plugin import Plugin
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/booster/plugin/__init__.py", line 1, in <module>
    from .gemini_plugin import GeminiPlugin
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/booster/plugin/gemini_plugin.py", line 31, in <module>
    from colossalai.zero import GeminiDDP, GeminiOptimizer
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/__init__.py", line 1, in <module>
    from .gemini import GeminiAdamOptimizer, GeminiDDP, GeminiOptimizer, get_static_torch_model
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/gemini/__init__.py", line 2, in <module>
    from .gemini_ddp import GeminiDDP
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/gemini/gemini_ddp.py", line 34, in <module>
    from .gemini_hook import GeminiZeROHook
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/gemini/gemini_hook.py", line 11, in <module>
    from colossalai.zero.gemini.gemini_mgr import GeminiManager
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/gemini/gemini_mgr.py", line 9, in <module>
    from .placement_policy import PlacementPolicyFactory
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/zero/gemini/placement_policy.py", line 10, in <module>
    from colossalai.legacy.utils.memory import colo_device_memory_capacity
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/__init__.py", line 1, in <module>
    from .initialize import (
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/initialize.py", line 21, in <module>
    from colossalai.legacy.amp import AMP_TYPE, convert_to_amp
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/amp/__init__.py", line 11, in <module>
    from .apex_amp import convert_to_apex_amp
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/amp/apex_amp/__init__.py", line 4, in <module>
    from .apex_amp import ApexAMPOptimizer
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/amp/apex_amp/apex_amp.py", line 14, in <module>
    from colossalai.legacy.utils import clip_grad_norm_fp32
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/utils/__init__.py", line 1, in <module>
    from .checkpointing import load_checkpoint, save_checkpoint
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/utils/checkpointing.py", line 16, in <module>
    from .common import is_using_pp
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/utils/common.py", line 16, in <module>
    from colossalai.legacy.tensor import ProcessGroup
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/tensor/__init__.py", line 6, in <module>
    from .tensor_spec import ColoTensorSpec
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/site-packages/colossalai/legacy/tensor/tensor_spec.py", line 10, in <module>
    @dataclass
     ^^^^^^^^^
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/chenhoujiang/miniconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'colossalai.legacy.tensor.distspec._DistSpec'> for field dist_attr is not allowed: use default_factory
```

**Comment by oahzxl** [comment]
maybe use python 3.10

**Comment by hjchen2** [comment]
> maybe use python 3.10

After downgrading to python3.10, there was no problem, thank you!
