### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by YuyangYin** [NUS-HPC-AI-Lab/OpenDiT#59]
Nice work！ Thanks for your efforts for open video diffusion model. When i try to run training code, the bug is as follows.
My command is : torchrun --standalone --nproc_per_node=2 train.py --model DiT-XL/2 --batch_size 2 --data_path ./videos
I have set use_video=True. I print the patch_size and find it out of subscriptable. It is the code bug? Looking for your reply! Thanks

Traceback (most recent call last):
File "/mnt/efs/home/yuyang/OpenDiT/train.py", line 358, in
main(args)
File "/mnt/efs/home/yuyang/OpenDiT/train.py", line 149, in main
DiT_models[args.model](
File "/mnt/efs/home/yuyang/OpenDiT/opendit/models/dit.py", line 787, in DiT_XL_2
return DiT(depth=28, hidden_size=1152, patch_size=2, num_heads=16, **kwargs)
File "/mnt/efs/home/yuyang/OpenDiT/opendit/models/dit.py", line 548, in init
self.num_patches = np.prod([input_size[i] // patch_size[i] for i in range(3)])
File "/mnt/efs/home/yuyang/OpenDiT/opendit/models/dit.py", line 548, in
self.num_patches = np.prod([input_size[i] // patch_size[i] for i in range(3)])
TypeError: 'int' object is not subscriptable

print("input_size:", input_size)
print("patch_size:", patch_size)
input_size: [16, 32, 32]
patch_size: 2

**Comment by oahzxl** [comment]
you use the wrong model for video generation. please refer to our given script for the correct model name

**Comment by YuyangYin** [comment]
Oh, Thanks. 
I run 'bash train_video.sh', the bug is as follows. The bug reason is wired. How to fix that?  Looking for your reply! Thanks



2024-02-28 09:35:06] Beginning epoch 0...
Epoch 0:   0%|                                                                                                       | 0/2 [00:00<?, ?it/s][2024-02-28 09:35:12,778] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 5908) of binary: /mnt/efs/home/yuyang/conda_envs/py/bin/python3.10
Traceback (most recent call last):
  File "/mnt/efs/home/yuyang/conda_envs/py/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
train.py FAILED
------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-28_09:35:12
  host      : a100-node5
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 5909)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 5909
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-28_09:35:12
  host      : a100-node5
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 5908)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 5908
======================================================

**Comment by oahzxl** [comment]
sorry that i cant give u any advice if no bug reason. can u try to print more detailed log?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: YuyangYin ***@***.***>
发送时间: Wednesday, February 28, 2024 5:38:12 PM
收件人: NUS-HPC-AI-Lab/OpenDiT ***@***.***>
抄送: Xuanlei Zhao ***@***.***>; Comment ***@***.***>
主题: Re: [NUS-HPC-AI-Lab/OpenDiT] TypeError: 'int' object is not subscriptable (Issue #59)


Oh, Thanks.
I run 'bash train_video.sh', the bug is as follows. The bug reason is wired. How to fix that? Looking for your reply! Thanks

2024-02-28 09:35:06] Beginning epoch 0...
Epoch 0: 0%| | 0/2 [00:00<?, ?it/s][2024-02-28 09:35:12,778] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 5908) of binary: /mnt/efs/home/yuyang/conda_envs/py/bin/python3.10
Traceback (most recent call last):
File "/mnt/efs/home/yuyang/conda_envs/py/bin/torchrun", line 8, in
sys.exit(main())
File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/init.py", line 347, in wrapper
return f(*args, **kwargs)
File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
run(args)
File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
elastic_launch(
File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
train.py FAILED
Failures:
[1]:
time : 2024-02-28_09:35:12
host : a100-node5
rank : 1 (local_rank: 1)
exitcode : -11 (pid: 5909)
error_file: <N/A>
traceback : Signal 11 (SIGSEGV) received by PID 5909
Root Cause (first observed failure):
[0]:
time : 2024-02-28_09:35:12
host : a100-node5
rank : 0 (local_rank: 0)
exitcode : -11 (pid: 5908)
error_file: <N/A>
traceback : Signal 11 (SIGSEGV) received by PID 5908

―

**Comment by YuyangYin** [comment]
(/mnt/efs/home/yuyang/conda_envs/py) torchrun --standalone --nproc_per_node=2 train.py \
>     --model vDiT-XL/222 \
>     --use_video \
>     --data_path ./videos/demo.csv \
>     --batch_size 1 \
>     --num_frames 16 \
>     --image_size 256 \
>     --frame_interval 3
[2024-02-28 09:34:22,516] torch.distributed.run: [WARNING] 
[2024-02-28 09:34:22,516] torch.distributed.run: [WARNING] *****************************************
[2024-02-28 09:34:22,516] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-02-28 09:34:22,516] torch.distributed.run: [WARNING] *****************************************
/mnt/efs/home/yuyang/ColossalAI/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
/mnt/efs/home/yuyang/ColossalAI/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.
  warnings.warn(
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/mnt/efs/home/yuyang/ColossalAI/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.
  warnings.warn("`config` is deprecated and will be removed soon.")
[02/28/24 09:34:41] INFO     colossalai - colossalai - INFO: /mnt/efs/home/yuyang/ColossalAI/colossalai/initialize.py:67 launch            
                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized, world size: 2                         
[2024-02-28 09:34:43] Experiment directory created at ./outputs/014-vDiT-XL-222
input_size: [16, 32, 32]
patch_size: (2, 2, 2)
input_size: [16, 32, 32]
patch_size: (2, 2, 2)
[2024-02-28 09:34:53] Model params: 705.58 M
input_size: [16, 32, 32]
patch_size: (2, 2, 2)
input_size: [16, 32, 32]
patch_size: (2, 2, 2)
[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now
[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now
[extension] Time taken to compile cpu_adam_x86 op: 0.24216032028198242 seconds
[extension] Compiling the JIT fused_optim_cuda kernel during runtime now
[extension] Time taken to compile fused_optim_cuda op: 2.2241833209991455 seconds
/mnt/efs/home/yuyang/ColossalAI/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = torch.cuda.IntTensor([0])
[2024-02-28 09:35:05] Dataset contains 4 images (./videos/demo.csv)
[extension] Time taken to compile cpu_adam_x86 op: 2.4108588695526123 seconds
[extension] Compiling the JIT fused_optim_cuda kernel during runtime now
[2024-02-28 09:35:05] Boost model for distributed training
[2024-02-28 09:35:05] Training for 1400 epochs...
[extension] Time taken to compile fused_optim_cuda op: 0.22110319137573242 seconds
/mnt/efs/home/yuyang/ColossalAI/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = torch.cuda.IntTensor([0])
[2024-02-28 09:35:06] Beginning epoch 0...
Epoch 0:   0%|                                                                                                       | 0/2 [00:00<?, ?it/s][2024-02-28 09:35:12,778] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 5908) of binary: /mnt/efs/home/yuyang/conda_envs/py/bin/python3.10
Traceback (most recent call last):
  File "/mnt/efs/home/yuyang/conda_envs/py/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/efs/home/yuyang/conda_envs/py/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
train.py FAILED
------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-28_09:35:12
  host      : a100-node5
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 5909)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 5909
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-28_09:35:12
  host      : a100-node5
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 5908)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 5908

**Comment by YuyangYin** [comment]
The whole terminal is above. Thank you for your patience.

**Comment by oahzxl** [comment]
still no clue. u can first check if the program is out of the system memory.
if not, u can try to use torch.cuda.synchronize() and print to identify where it exits
