### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.distributed._functional_collectives'

### ISSUE THREAD

**Issue by gongshaojie12** [NUS-HPC-AI-Lab/OpenDiT#88]
When I run the command:

`python sample.py --model DiT-XL/2 --image_size 256 --ckpt ./DiT-XL-2-256x256.pt`

It encountered the following error

```
Traceback (most recent call last):
  File "/home/ai/nlp/OpenDiT/sample.py", line 19, in <module>
    from opendit.models.dit import DiT_models
  File "/home/ai/nlp/OpenDiT/opendit/models/dit.py", line 27, in <module>
    from opendit.utils.operation import AllGather, AsyncAllGatherForTwo, all_to_all_comm, gather_forward_split_backward
  File "/home/ai/nlp/OpenDiT/opendit/utils/operation.py", line 9, in <module>
    from torch.distributed._functional_collectives import all_gather_tensor, reduce_scatter_tensor
ModuleNotFoundError: No module named 'torch.distributed._functional_collectives'
```

What is the issue? How can it be resolved? Thank you!

**Comment by oahzxl** [comment]
update to the latest code or just remove this line. it will be used only for async sequence parallel
